apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-otsugua-deployment-3
  namespace: otsugua04-dev
  labels:
    app: mi-app-otsugua-3
    areanegocio: tecnologia
spec:
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      app: mi-app-otsugua-3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mi-app-otsugua-3
    spec:
      containers:
      - name: mi-app-container
        image: otsugua04/hola-mundo-service1:build-{{ .Values.container.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          requests:
            cpu: {{ .Values.container.cpuRequests }}
            memory: {{ .Values.container.memoryRequests }}
          limits:
            cpu: {{ .Values.container.cpuLimits }}
            memory: {{ .Values.container.memoryLimits }}
        envFrom:
            - configMapRef:
                name: mi-configmap-otsugua
            - secretRef:
                name: mi-secret-otsugua
        startupProbe:
          httpGet:
            path: /startup
            port: {{ .Values.container.port }}
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.container.port }}
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.container.port }}
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10