apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-{{ .Values.name }}
  namespace: {{ .Values.namespace }}  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: {{ .Values.name }}  # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}        # Puerto del Service
      targetPort: {{ .Values.container.port }}  # Puerto del contenedor
  type: {{ .Values.service.type }}     # Cambia a NodePort o LoadBalancer si quieres acceso externo

